---
services:

  bk-developer:
    command: /bin/sh -c "while sleep 1000; do :; done"
    container_name: bk-dev-container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      DISPLAY: ${DISPLAY}
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    image: bk-dev-docker:latest
    network_mode: "host"
    privileged: true
    runtime: nvidia
    volumes:
      - /dev/shm:/dev/shm
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.ssh:/root/.ssh-localhost:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
